### ISSUE TITLE
Get Sports data error

### ISSUE THREAD

**Issue by AsianPsychoBoy** [MyMICDS/MyMICDS-v2#19]
When running latest angular frontend on dev branch and backend server on master branch, sports js raises this error whenever a request for scores has been made: 
```
Unable to select database
^

SyntaxError: Unexpected token U in JSON at position 0
    at Object.parse (native)
    at Request._callback (D:\Github\MyMICDS-v2\src\libs\sports.js:40:15)
    at Request.self.callback (D:\Github\MyMICDS-v2\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\Github\MyMICDS-v2\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\Github\MyMICDS-v2\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
```

**Comment by michaelgira23** [comment]
The Rams Army app doesn't have many score updates. As such, we probably don't need to worry about this.
